QUESTIONS_ORDER = [
    ("departure", "Adresse de départ", True),
    ("arrival", "Adresse d’arrivée", True),
    ("date", "Date du transport (JJ/MM/AAAA)", True),
    ("time", "Heure du transport (HH:MM)", True),
    ("first name", "Prénom", True),
    ("last name", "Nom de famille", True),
    ("phone", "Numéro de téléphone", True),
    ("date_of_birth", "Date de naissance (facultatif)", False),
    ("ald", "ALD (oui/non, facultatif)", False),
    ("num_secu", "Numéro de sécurité sociale (facultatif)", False),
    ("cash register", "Caisse d’affiliation (facultatif)", False),
    ("prescription", "Prescription médicale (oui/non, facultatif)", False),
    ("transport_voucher", "Bon de transport (oui/non, facultatif)", False),
    ("wheelchair", "Fauteuil roulant nécessaire (oui/non, facultatif)", False),
    ("people", "Nombre d’accompagnants (facultatif)", False),
    ("baby_seat", "Siège bébé nécessaire (oui/non, facultatif)", False),
    ("others", "Autres informations (facultatif)", False),
    ("email", "Adresse e-mail (facultatif)", False),
]
